### ISSUE TITLE
Stopped working for the version 2017.3.4

### ISSUE THREAD

**Issue by iHmD** [dingdayu/jetbrians#1]
As mentioned in the title, the license is not working anymore for the new versions of the Jetbrains products.

**Comment by dingdayu** [comment]
Thank you for your feedback, a few days before the Chinese New Year, has been in a state of no network, I will test as soon as possible.

**Comment by dingdayu** [comment]
![image](https://user-images.githubusercontent.com/2040348/36529002-ebb1d742-17f1-11e8-8651-a626bf05efaa.png)

**Comment by dingdayu** [comment]
![image](https://user-images.githubusercontent.com/2040348/36529262-ce52f25c-17f2-11e8-9812-d511f9077132.png)

**Comment by dingdayu** [comment]
After testing, it should be usable.

Can you provide more information?

**Comment by thiagogjt** [comment]
2018/03/01 15:53:02 Starting server (v0.2.0) licensed to: dingdayu
2018/03/01 15:53:02 Starting server at http://0.0.0.0:1128
2018/03/01 15:53:02 Quit the server with CTRL-C.
2018/03/01 15:53:30 172.17.0.1:45386 2017.3.4 Build IU-173.4548.28 2017300

![image](https://user-images.githubusercontent.com/645187/36854424-bad1d1fa-1d4f-11e8-88f3-57790958ec6a.png)

**Comment by dingdayu** [comment]
Please avoid using localhost.
Try to customize host.

**Comment by dingdayu** [comment]
If it is useful, please tell me.

**Comment by iHmD** [comment]
![screenshot from 2018-03-03 13-52-13](https://user-images.githubusercontent.com/6934421/36935104-d51bf72e-1eea-11e8-97ec-9620f5ddd847.png)

**Comment by dingdayu** [comment]
@iHmD Please contact me by email.

614422099@qq.com
